### ISSUE TITLE
is there any way to save the data to a variable rather than a file?

### ISSUE THREAD

**Issue by alindzon** [sathyapulse/angular-recorder#12]
I plan to write the audio to a sql database as base64 wav rather than a separate file.

I assume I can access the data in the recorder.audioModel

so something like 
$scope.recording=recorder.audioModel.data;

**Comment by traecadenhead** [comment]
I've been banging my head against this question as well. No mater what I use as my audio-model, when I try to access it in my controller it's showing up as null. Seems like this should be a simple thing, but I've tried all kinds of things to get it to work and nothing is working.

**Comment by OllieStudio** [comment]
Hi guys, got it using:

$scope.saveAudio = function(){
		$scope.audiofile = $window.audioInput.children[1].currentSrc;
	  };

Where _audioInput_ is my directive id:

<ng-audio-recorder id="audioInput"...

**Comment by ajmeyghani** [comment]
@traecadenhead , It seems like you can get the blob in the next digest cycle when the recording has finished using `on-record-complete`:

```javascript
angular.module('app', ['angularAudioRecorder'])
.config(['recorderServiceProvider', function(recorderServiceProvider){
}])
.controller('recorderCtrl', function($scope, $timeout) {
  $scope.logResult = function() {
    $timeout(function() {
      console.log($scope.recordedInput);
    });
  };
});
```

```html
<body ng-controller="recorderCtrl">
  <ng-audio-recorder id='audioInput' audio-model='recordedInput' on-record-complete='logResult()'>
    <div ng-if="recorder.isAvailable">
      <button ng-click="recorder.startRecord()" type="button" ng-disabled="recorder.status.isRecording">
          Start Record
      </button>
      <button ng-click="recorder.stopRecord()" type="button" ng-disabled="recorder.status.isRecording === false">
          Stop Record
      </button>
      <button ng-click="recorder.playbackRecording()" type="button"
              ng-disabled="recorder.status.isRecording || !recorder.audioModel">
          Play Back
      </button>
    </div>
    <div ng-if="!recorder.isAvailable">
      Message for users when recording is not possible.
    </div>
  </ng-audio-recorder>
</body>
```

The key is the `on-record-complete` callback:

```html
<ng-audio-recorder id='audioInput' audio-model='recordedInput' on-record-complete='logResult()'>
```
